version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: crypto
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d crypto"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7

  app:
    build: .
    ports:
      - "8001:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  celery:
    build: .
    command: celery -A app.tasks worker --beat --loglevel=info
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started





